enfermedades.add("Abrasión corneal");
enfermedades.add("Accidentes de tráfico");
enfermedades.add("Accidentes eléctricos");
enfermedades.add("Accidentes en el agua");
enfermedades.add("Accidentes químicos");
enfermedades.add("Acné");
enfermedades.add("Aftas bucales");
enfermedades.add("Albinismo");
enfermedades.add("Alcoholismo");
enfermedades.add("Alergia");
enfermedades.add("Alergia al níquel");
enfermedades.add("Alergia al sol");
enfermedades.add("Alud");
enfermedades.add("Alzhéimer");
enfermedades.add("Amenorrea");
enfermedades.add("Ampollas");
enfermedades.add("Anemia");
enfermedades.add("Aneurisma");
enfermedades.add("Angina de pecho");
enfermedades.add("Anisakiasis");
enfermedades.add("Anorexia");
enfermedades.add("Ansiedad");
enfermedades.add("Apendicitis");
enfermedades.add("Apnea del sueño");
enfermedades.add("Arritmia");
enfermedades.add("Arteriosclerosis");
enfermedades.add("Artritis reumatoide");
enfermedades.add("Artrosis");
enfermedades.add("Ascitis");
enfermedades.add("Asma");
enfermedades.add("Astigmatismo");
enfermedades.add("Ataxia");
enfermedades.add("Atragantamiento");
enfermedades.add("Atrofia vaginal");
enfermedades.add("Autismo");
enfermedades.add("Balanitis");
enfermedades.add("Bartolinitis");
enfermedades.add("Bocio");
enfermedades.add("Botulismo");
enfermedades.add("Bronquiectasias");
enfermedades.add("Bronquiolitis obliterante");
enfermedades.add("Bronquitis");
enfermedades.add("Brucelosis");
enfermedades.add("Bruxismo");
enfermedades.add("Bulimia");
enfermedades.add("Campylobacter");
enfermedades.add("Cáncer");
enfermedades.add("Cáncer de cabeza y cuello");
enfermedades.add("Cáncer de colon");
enfermedades.add("Cáncer de cuello de útero");
enfermedades.add("Cáncer de esófago");
enfermedades.add("Cáncer de estómago");
enfermedades.add("Cáncer de hígado");
enfermedades.add("Cáncer de laringe");
enfermedades.add("Cáncer de mama");
enfermedades.add("Cáncer de ovario");
enfermedades.add("Cáncer de páncreas");
enfermedades.add("Cáncer de pene");
enfermedades.add("Cáncer de piel");
enfermedades.add("Cáncer de próstata");
enfermedades.add("Cáncer de pulmón");
enfermedades.add("Cáncer de riñón");
enfermedades.add("Cáncer de testículo");
enfermedades.add("Cáncer de tiroides");
enfermedades.add("Cáncer de vejiga");
enfermedades.add("Cáncer oral");
enfermedades.add("Cáncer óseo");
enfermedades.add("Candidiasis");
enfermedades.add("Carbunco");
enfermedades.add("Cataratas");
enfermedades.add("Catarro");
enfermedades.add("Celiaquía");
enfermedades.add("Chancroide");
enfermedades.add("Chikungunya");
enfermedades.add("Ciática");
enfermedades.add("Cirrosis");
enfermedades.add("Cistitis");
enfermedades.add("Citomegalovirus");
enfermedades.add("Clamidia");
enfermedades.add("Cólera");
enfermedades.add("Colesteatoma");
enfermedades.add("Cólico nefrítico");
enfermedades.add("Colitis ulcerosa");
enfermedades.add("Colon irritable");
enfermedades.add("Congelamiento");
enfermedades.add("Congestión nasal");
enfermedades.add("Conjuntivitis");
enfermedades.add("Contusiones");
enfermedades.add("Corte de digestión");
enfermedades.add("Crisis de pánico");
enfermedades.add("Cuerpos extraños");
enfermedades.add("Daltonismo");
enfermedades.add("Déficit de la hormona del crecimiento");
enfermedades.add("Degeneración macular");
enfermedades.add("Demencia");
enfermedades.add("Demencia con cuerpos de Lewy");
enfermedades.add("Demencia vascular");
enfermedades.add("Dengue");
enfermedades.add("Depresión");
enfermedades.add("Dermatitis atópica");
enfermedades.add("Derrame ocular");
enfermedades.add("Deterioro cognitivo leve");
enfermedades.add("Diabetes");
enfermedades.add("Diabetes gestacional");
enfermedades.add("Diabetes insípida");
enfermedades.add("Difteria");
enfermedades.add("Disfunción eréctil");
enfermedades.add("Dislexia");
enfermedades.add("Dismenorrea");
enfermedades.add("Dispepsia");
enfermedades.add("Distonía");
enfermedades.add("Distrofia muscular de Duchenne");
enfermedades.add("Diverticulosis");
enfermedades.add("Ébola");
enfermedades.add("Edema pulmonar");
enfermedades.add("Elefantiasis");
enfermedades.add("Encefalitis");
enfermedades.add("Endocarditis");
enfermedades.add("Endometriosis");
enfermedades.add("Enfermedad de Addison");
enfermedades.add("Enfermedad de Behçet");
enfermedades.add("Enfermedad de Chagas");
enfermedades.add("Enfermedad de Crohn");
enfermedades.add("Enfermedad de Huntington");
enfermedades.add("Enfermedad de Kawasaki");
enfermedades.add("Enfermedad de La Peyronie");
enfermedades.add("Enfermedad de Lyme");
enfermedades.add("Enfermedad de Paget");
enfermedades.add("Enfermedad de Wilson");
enfermedades.add("Enfermedad inflamatoria pélvica");
enfermedades.add("Enfermedades de Transmisión Sexual");
enfermedades.add("Enfermedades raras");
enfermedades.add("Epilepsia");
enfermedades.add("EPOC");
enfermedades.add("Escleritis");
enfermedades.add("Esclerodermia");
enfermedades.add("Esclerosis lateral amiotrófica");
enfermedades.add("Esclerosis múltiple");
enfermedades.add("Escoliosis");
enfermedades.add("Esófago de Barrett");
enfermedades.add("Espondilitis anquilosante");
enfermedades.add("Esquizofrenia");
enfermedades.add("Esteatosis hepática");
enfermedades.add("Estrabismo");
enfermedades.add("Estreñimiento");
enfermedades.add("Eyaculación precoz");
enfermedades.add("Faringitis");
enfermedades.add("Fascitis plantar");
enfermedades.add("Fenilcetonuria");
enfermedades.add("Fibrilación auricular");
enfermedades.add("Fibromialgia");
enfermedades.add("Fibrosis quística");
enfermedades.add("Fiebre amarilla");
enfermedades.add("Fiebre de Lassa");
enfermedades.add("Fiebre de Oropouche");
enfermedades.add("Fiebre del valle del Rift");
enfermedades.add("Fiebre hemorrágica de Crimea-Congo");
enfermedades.add("Fiebre tifoidea");
enfermedades.add("Fístula anal");
enfermedades.add("Fractura de dedo");
enfermedades.add("Fractura nasal");
enfermedades.add("Galactorrea");
enfermedades.add("Galactosemia");
enfermedades.add("Gastritis");
enfermedades.add("Gastroenteritis");
enfermedades.add("Giardiasis");
enfermedades.add("Glaucoma");
enfermedades.add("Golpe de calor");
enfermedades.add("Gonorrea");
enfermedades.add("Gota");
enfermedades.add("Gripe");
enfermedades.add("Hantavirus");
enfermedades.add("Hemocromatosis");
enfermedades.add("Hemofilia");
enfermedades.add("Hemorragia nasal");
enfermedades.add("Hemorroides");
enfermedades.add("Hepatitis");
enfermedades.add("Herida por arma de fuego");
enfermedades.add("Heridas");
enfermedades.add("Hernia de hiato");
enfermedades.add("Hernia discal");
enfermedades.add("Hernia inguinal");
enfermedades.add("Herpes");
enfermedades.add("Herpes zóster");
enfermedades.add("Hidatidosis");
enfermedades.add("Hiperactividad (TDAH)");
enfermedades.add("Hipercolesterolemia");
enfermedades.add("Hipermetropía");
enfermedades.add("Hiperplasia benigna de próstata");
enfermedades.add("Hipertensión arterial");
enfermedades.add("Hipertiroidismo");
enfermedades.add("Hipoacusia");
enfermedades.add("Hipocalcemia");
enfermedades.add("Hipoglucemia");
enfermedades.add("Hipogonadismo");
enfermedades.add("Hipotensión arterial");
enfermedades.add("Hipotermia");
enfermedades.add("Hipotiroidismo");
enfermedades.add("Hirsutismo");
enfermedades.add("Ictus");
enfermedades.add("Impétigo");
enfermedades.add("Incendios");
enfermedades.add("Incontinencia urinaria");
enfermedades.add("Infarto de miocardio");
enfermedades.add("Infecciones urinarias");
enfermedades.add("Insomnio");
enfermedades.add("Insomnio familiar fatal");
enfermedades.add("Insuficiencia cardiaca");
enfermedades.add("Insuficiencia hepática");
enfermedades.add("Insuficiencia mitral");
enfermedades.add("Insuficiencia renal crónica");
enfermedades.add("Intolerancia a la histamina");
enfermedades.add("Intoxicación etílica");
enfermedades.add("Intoxicación por monóxido de carbono");
enfermedades.add("Intoxicaciones");
enfermedades.add("Juanetes");
enfermedades.add("Ladillas");
enfermedades.add("Laringitis");
enfermedades.add("Legionella");
enfermedades.add("Leishmaniasis");
enfermedades.add("Lepra");
enfermedades.add("Leptospirosis");
enfermedades.add("Lesiones maxilares");
enfermedades.add("Leucemia");
enfermedades.add("Lipodistrofia");
enfermedades.add("Lipotimia");
enfermedades.add("Listeriosis");
enfermedades.add("Litiasis biliar");
enfermedades.add("Lumbalgia");
enfermedades.add("Lupus");
enfermedades.add("Luxaciones");
enfermedades.add("Mal agudo de montaña");
enfermedades.add("Malaria");
enfermedades.add("Melanoma");
enfermedades.add("Melasma");
enfermedades.add("Melioidosis");
enfermedades.add("Meningitis");
enfermedades.add("Menopausia");
enfermedades.add("MERS");
enfermedades.add("Mesotelioma");
enfermedades.add("Miastenia gravis");
enfermedades.add("Micoplasma genital");
enfermedades.add("Microcefalia");
enfermedades.add("Mieloma múltiple");
enfermedades.add("Migraña");
enfermedades.add("Miomatosis uterina");
enfermedades.add("Miopía");
enfermedades.add("Molusco contagioso");
enfermedades.add("Mononucleosis");
enfermedades.add("Mordeduras de animales");
enfermedades.add("Narcolepsia");
enfermedades.add("Neumonía");
enfermedades.add("Neumotórax");
enfermedades.add("Neuralgia del trigémino");
enfermedades.add("Neurofibromatosis");
enfermedades.add("Nistagmo");
enfermedades.add("Norovirus");
enfermedades.add("Obesidad");
enfermedades.add("Obesidad infantil");
enfermedades.add("Ojo seco");
enfermedades.add("Oncocercosis");
enfermedades.add("Onicomicosis");
enfermedades.add("Orquitis");
enfermedades.add("Osteomalacia");
enfermedades.add("Osteomielitis");
enfermedades.add("Osteonecrosis");
enfermedades.add("Osteoporosis");
enfermedades.add("Otitis");
enfermedades.add("Palpitaciones cardíacas");
enfermedades.add("Pancreatitis");
enfermedades.add("Paperas");
enfermedades.add("Parálisis cerebral");
enfermedades.add("Párkinson");
enfermedades.add("Patologías benignas de mama");
enfermedades.add("Pericarditis");
enfermedades.add("Peritonitis");
enfermedades.add("Peste");
enfermedades.add("Pian");
enfermedades.add("Picaduras de insectos");
enfermedades.add("Pie de atleta");
enfermedades.add("Pielonefritis");
enfermedades.add("Pitiriasis versicolor");
enfermedades.add("Policitemia vera");
enfermedades.add("Poliomielitis");
enfermedades.add("Pólipos uterinos");
enfermedades.add("Prediabetes");
enfermedades.add("Presbiacusia");
enfermedades.add("Presbicia");
enfermedades.add("Priapismo");
enfermedades.add("Prostatitis");
enfermedades.add("Psoriasis");
enfermedades.add("PTI (trombocitopenia inmune primaria)");
enfermedades.add("Quemaduras");
enfermedades.add("Rabia");
enfermedades.add("Raspaduras y laceraciones");
enfermedades.add("Reacciones alérgicas a medicamentos");
enfermedades.add("Reanimación cardiopulmonar");
enfermedades.add("Reflujo gastroesofágico");
enfermedades.add("Rescate en montaña");
enfermedades.add("Resistencia a la insulina");
enfermedades.add("Retinosis pigmentaria");
enfermedades.add("Rinitis");
enfermedades.add("Rizartrosis");
enfermedades.add("Rosácea");
enfermedades.add("Rubéola");
enfermedades.add("Salmonelosis");
enfermedades.add("Sarampión");
enfermedades.add("Sarcoidosis");
enfermedades.add("Sarcoma de tejidos blandos");
enfermedades.add("Sarna");
enfermedades.add("Sensibilidad química múltiple");
enfermedades.add("Sepsis");
enfermedades.add("Shigelosis");
enfermedades.add("Shock");
enfermedades.add("SIBO");
enfermedades.add("SIDA");
enfermedades.add("Sífilis");
enfermedades.add("Síndrome de Angelman");
enfermedades.add("Síndrome de Cushing");
enfermedades.add("Síndrome de Down");
enfermedades.add("Síndrome de fatiga crónica");
enfermedades.add("Síndrome de Guillain-Barré");
enfermedades.add("Síndrome de Klinefelter");
enfermedades.add("Síndrome de Lynch");
enfermedades.add("Síndrome de Marfan");
enfermedades.add("Síndrome de Noonan");
enfermedades.add("Síndrome de Ovario Poliquístico (SOP)");
enfermedades.add("Síndrome de Patau");
enfermedades.add("Síndrome de piernas inquietas");
enfermedades.add("Síndrome de Rett");
enfermedades.add("Síndrome de Reye");
enfermedades.add("Síndrome de Sanfilippo");
enfermedades.add("Síndrome de Sjögren");
enfermedades.add("Síndrome de Tourette");
enfermedades.add("Síndrome de Turner");
enfermedades.add("Síndrome de Williams");
enfermedades.add("Síndrome de X Frágil");
enfermedades.add("Síndrome del túnel carpiano");
enfermedades.add("Síndrome metabólico");
enfermedades.add("Sinusitis");
enfermedades.add("Siringomielia");
enfermedades.add("Sobredosis");
enfermedades.add("Talasemia");
enfermedades.add("Telangiectasias");
enfermedades.add("Tendinitis");
enfermedades.add("Teniasis");
enfermedades.add("Terremotos");
enfermedades.add("Tétanos");
enfermedades.add("Tinnitus");
enfermedades.add("Tortícolis");
enfermedades.add("Tos ferina");
enfermedades.add("Toxicodermias");
enfermedades.add("Toxoplasmosis");
enfermedades.add("Tracoma");
enfermedades.add("Traqueítis");
enfermedades.add("Trastorno bipolar");
enfermedades.add("Trastorno obsesivo compulsivo");
enfermedades.add("Traumatismo craneal");
enfermedades.add("Tricomoniasis");
enfermedades.add("Tripanosomiasis africana");
enfermedades.add("Tromboembolismo pulmonar");
enfermedades.add("Trombosis venosa");
enfermedades.add("Tuberculosis");
enfermedades.add("Tularemia");
enfermedades.add("Tumores cerebrales");
enfermedades.add("Úlcera");
enfermedades.add("Uretritis");
enfermedades.add("Urticaria");
enfermedades.add("Uveítis");
enfermedades.add("Vaginitis");
enfermedades.add("Vaginosis bacteriana");
enfermedades.add("Varicela");
enfermedades.add("Varices");
enfermedades.add("Varicocele");
enfermedades.add("Vértigo");
enfermedades.add("Virus del Nilo Occidental");
enfermedades.add("Virus Mayaro");
enfermedades.add("Virus Nipah");
enfermedades.add("Virus Usutu");
enfermedades.add("Virus Zika");
enfermedades.add("Vitíligo");
enfermedades.add("VPH");